### ISSUE TITLE
List models: Error decoding response body

### ISSUE THREAD

**Issue by francois-caddet** [ivangabriele/mistralai-client-rs#15]
**Describe the bug**

When calling `Client::list_models`, it return the error: Error decoding response body.

**Reproduction**

1. run `cargo run --example=list_models`
2. run `cargo run --example=list_models_async`

**Expected behavior**

...Return the list of models.

**Screenshots**

**Version**

0.12.0

**Environment**

If applicable, add relevant information about your config and environment here.

**Comment by francois-caddet** [comment]
I don't see the permission field for the model description on the mistral.ai documentation. They may removed it.

**Comment by ivangabriele** [comment]
Indeed, the API response has changed. I just fixed it 2114916941e1ff5aa242290df5f092c0d4954afc.
